# Generated by Django 2.1.7 on 2019-07-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('deadline', models.DateField(verbose_name='返却日')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='著者')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='要約')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Eメールアドレス')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
