# Generated by Django 2.1.7 on 2019-07-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190709_0012'),
        ('books', '0004_auto_20190708_2233'),
    ]

    operations = [
    ]
